BEGIN
TRANSACTION;

INSERT INTO game.avatar (model_id, "level") VALUES
-- Set 1
('set1_character1_level1', 1),
('set1_character1_level2', 2),
('set1_character1_level3', 3),
('set1_character1_level4', 4),
('set1_character1_level5', 5),
('set1_character2_level1', 1),
('set1_character2_level2', 2),
('set1_character2_level3', 3),
('set1_character2_level4', 4),
('set1_character2_level5', 5),
('set1_character3_level1', 1),
('set1_character3_level2', 2),
('set1_character3_level3', 3),
('set1_character3_level4', 4),
('set1_character3_level5', 5),
('set1_character4_level1', 1),
('set1_character4_level2', 2),
('set1_character4_level3', 3),
('set1_character4_level4', 4),
('set1_character4_level5', 5),

-- Set 2
('set2_character1_level1', 1),
('set2_character1_level2', 2),
('set2_character1_level3', 3),
('set2_character1_level4', 4),
('set2_character1_level5', 5),
('set2_character2_level1', 1),
('set2_character2_level2', 2),
('set2_character2_level3', 3),
('set2_character2_level4', 4),
('set2_character2_level5', 5),
('set2_character3_level1', 1),
('set2_character3_level2', 2),
('set2_character3_level3', 3),
('set2_character3_level4', 4),
('set2_character3_level5', 5),
('set2_character4_level1', 1),
('set2_character4_level2', 2),
('set2_character4_level3', 3),
('set2_character4_level4', 4),
('set2_character4_level5', 5),

-- Set 3
('set3_character1_level1', 1),
('set3_character1_level2', 2),
('set3_character1_level3', 3),
('set3_character1_level4', 4),
('set3_character1_level5', 5),
('set3_character2_level1', 1),
('set3_character2_level2', 2),
('set3_character2_level3', 3),
('set3_character2_level4', 4),
('set3_character2_level5', 5),
('set3_character3_level1', 1),
('set3_character3_level2', 2),
('set3_character3_level3', 3),
('set3_character3_level4', 4),
('set3_character3_level5', 5),
('set3_character4_level1', 1),
('set3_character4_level2', 2),
('set3_character4_level3', 3),
('set3_character4_level4', 4),
('set3_character4_level5', 5),

-- Set 4
('set4_character1_level1', 1),
('set4_character1_level2', 2),
('set4_character1_level3', 3),
('set4_character1_level4', 4),
('set4_character1_level5', 5),
('set4_character2_level1', 1),
('set4_character2_level2', 2),
('set4_character2_level3', 3),
('set4_character2_level4', 4),
('set4_character2_level5', 5),
('set4_character3_level1', 1),
('set4_character3_level2', 2),
('set4_character3_level3', 3),
('set4_character3_level4', 4),
('set4_character3_level5', 5),
('set4_character4_level1', 1),
('set4_character4_level2', 2),
('set4_character4_level3', 3),
('set4_character4_level4', 4),
('set4_character4_level5', 5),

-- Set 5
('set5_character1_level1', 1),
('set5_character1_level2', 2),
('set5_character1_level3', 3),
('set5_character1_level4', 4),
('set5_character1_level5', 5),
('set5_character2_level1', 1),
('set5_character2_level2', 2),
('set5_character2_level3', 3),
('set5_character2_level4', 4),
('set5_character2_level5', 5),
('set5_character3_level1', 1),
('set5_character3_level2', 2),
('set5_character3_level3', 3),
('set5_character3_level4', 4),
('set5_character3_level5', 5),
('set5_character4_level1', 1),
('set5_character4_level2', 2),
('set5_character4_level3', 3),
('set5_character4_level4', 4),
('set5_character4_level5', 5)
ON CONFLICT (model_id) DO NOTHING;

INSERT INTO game.game_asset (model_id, url) VALUES
-- Set 1
('set1_character1_level1', 'Model/Set1/character1/level1.fbx'),
('set1_character1_level2', 'Model/Set1/character1/level2.fbx'),
('set1_character1_level3', 'Model/Set1/character1/level3.fbx'),
('set1_character1_level4', 'Model/Set1/character1/level4.fbx'),
('set1_character1_level5', 'Model/Set1/character1/level5.fbx'),
('set1_character2_level1', 'Model/Set1/character2/level1.fbx'),
('set1_character2_level2', 'Model/Set1/character2/level2.fbx'),
('set1_character2_level3', 'Model/Set1/character2/level3.fbx'),
('set1_character2_level4', 'Model/Set1/character2/level4.fbx'),
('set1_character2_level5', 'Model/Set1/character2/level5.fbx'),
('set1_character3_level1', 'Model/Set1/character3/level1.fbx'),
('set1_character3_level2', 'Model/Set1/character3/level2.fbx'),
('set1_character3_level3', 'Model/Set1/character3/level3.fbx'),
('set1_character3_level4', 'Model/Set1/character3/level4.fbx'),
('set1_character3_level5', 'Model/Set1/character3/level5.fbx'),
('set1_character4_level1', 'Model/Set1/character4/level1.fbx'),
('set1_character4_level2', 'Model/Set1/character4/level2.fbx'),
('set1_character4_level3', 'Model/Set1/character4/level3.fbx'),
('set1_character4_level4', 'Model/Set1/character4/level4.fbx'),
('set1_character4_level5', 'Model/Set1/character4/level5.fbx'),

-- Set 2
('set2_character1_level1', 'Model/Set2/character1/level1.fbx'),
('set2_character1_level2', 'Model/Set2/character1/level2.fbx'),
('set2_character1_level3', 'Model/Set2/character1/level3.fbx'),
('set2_character1_level4', 'Model/Set2/character1/level4.fbx'),
('set2_character1_level5', 'Model/Set2/character1/level5.fbx'),
('set2_character2_level1', 'Model/Set2/character2/level1.fbx'),
('set2_character2_level2', 'Model/Set2/character2/level2.fbx'),
('set2_character2_level3', 'Model/Set2/character2/level3.fbx'),
('set2_character2_level4', 'Model/Set2/character2/level4.fbx'),
('set2_character2_level5', 'Model/Set2/character2/level5.fbx'),
('set2_character3_level1', 'Model/Set2/character3/level1.fbx'),
('set2_character3_level2', 'Model/Set2/character3/level2.fbx'),
('set2_character3_level3', 'Model/Set2/character3/level3.fbx'),
('set2_character3_level4', 'Model/Set2/character3/level4.fbx'),
('set2_character3_level5', 'Model/Set2/character3/level5.fbx'),
('set2_character4_level1', 'Model/Set2/character4/level1.fbx'),
('set2_character4_level2', 'Model/Set2/character4/level2.fbx'),
('set2_character4_level3', 'Model/Set2/character4/level3.fbx'),
('set2_character4_level4', 'Model/Set2/character4/level4.fbx'),
('set2_character4_level5', 'Model/Set2/character4/level5.fbx'),

-- Set 3
('set3_character1_level1', 'Model/Set3/character1/level1.fbx'),
('set3_character1_level2', 'Model/Set3/character1/level2.fbx'),
('set3_character1_level3', 'Model/Set3/character1/level3.fbx'),
('set3_character1_level4', 'Model/Set3/character1/level4.fbx'),
('set3_character1_level5', 'Model/Set3/character1/level5.fbx'),
('set3_character2_level1', 'Model/Set3/character2/level1.fbx'),
('set3_character2_level2', 'Model/Set3/character2/level2.fbx'),
('set3_character2_level3', 'Model/Set3/character2/level3.fbx'),
('set3_character2_level4', 'Model/Set3/character2/level4.fbx'),
('set3_character2_level5', 'Model/Set3/character2/level5.fbx'),
('set3_character3_level1', 'Model/Set3/character3/level1.fbx'),
('set3_character3_level2', 'Model/Set3/character3/level2.fbx'),
('set3_character3_level3', 'Model/Set3/character3/level3.fbx'),
('set3_character3_level4', 'Model/Set3/character3/level4.fbx'),
('set3_character3_level5', 'Model/Set3/character3/level5.fbx'),
('set3_character4_level1', 'Model/Set3/character4/level1.fbx'),
('set3_character4_level2', 'Model/Set3/character4/level2.fbx'),
('set3_character4_level3', 'Model/Set3/character4/level3.fbx'),
('set3_character4_level4', 'Model/Set3/character4/level4.fbx'),
('set3_character4_level5', 'Model/Set3/character4/level5.fbx'),

-- Set 4
('set4_character1_level1', 'Model/Set4/character1/level1.fbx'),
('set4_character1_level2', 'Model/Set4/character1/level2.fbx'),
('set4_character1_level3', 'Model/Set4/character1/level3.fbx'),
('set4_character1_level4', 'Model/Set4/character1/level4.fbx'),
('set4_character1_level5', 'Model/Set4/character1/level5.fbx'),
('set4_character2_level1', 'Model/Set4/character2/level1.fbx'),
('set4_character2_level2', 'Model/Set4/character2/level2.fbx'),
('set4_character2_level3', 'Model/Set4/character2/level3.fbx'),
('set4_character2_level4', 'Model/Set4/character2/level4.fbx'),
('set4_character2_level5', 'Model/Set4/character2/level5.fbx'),
('set4_character3_level1', 'Model/Set4/character3/level1.fbx'),
('set4_character3_level2', 'Model/Set4/character3/level2.fbx'),
('set4_character3_level3', 'Model/Set4/character3/level3.fbx'),
('set4_character3_level4', 'Model/Set4/character3/level4.fbx'),
('set4_character3_level5', 'Model/Set4/character3/level5.fbx'),
('set4_character4_level1', 'Model/Set4/character4/level1.fbx'),
('set4_character4_level2', 'Model/Set4/character4/level2.fbx'),
('set4_character4_level3', 'Model/Set4/character4/level3.fbx'),
('set4_character4_level4', 'Model/Set4/character4/level4.fbx'),
('set4_character4_level5', 'Model/Set4/character4/level5.fbx'),

-- Set 5
('set5_character1_level1', 'Model/Set5/character1/level1.fbx'),
('set5_character1_level2', 'Model/Set5/character1/level2.fbx'),
('set5_character1_level3', 'Model/Set5/character1/level3.fbx'),
('set5_character1_level4', 'Model/Set5/character1/level4.fbx'),
('set5_character1_level5', 'Model/Set5/character1/level5.fbx'),
('set5_character2_level1', 'Model/Set5/character2/level1.fbx'),
('set5_character2_level2', 'Model/Set5/character2/level2.fbx'),
('set5_character2_level3', 'Model/Set5/character2/level3.fbx'),
('set5_character2_level4', 'Model/Set5/character2/level4.fbx'),
('set5_character2_level5', 'Model/Set5/character2/level5.fbx'),
('set5_character3_level1', 'Model/Set5/character3/level1.fbx'),
('set5_character3_level2', 'Model/Set5/character3/level2.fbx'),
('set5_character3_level3', 'Model/Set5/character3/level3.fbx'),
('set5_character3_level4', 'Model/Set5/character3/level4.fbx'),
('set5_character3_level5', 'Model/Set5/character3/level5.fbx'),
('set5_character4_level1', 'Model/Set5/character4/level1.fbx'),
('set5_character4_level2', 'Model/Set5/character4/level2.fbx'),
('set5_character4_level3', 'Model/Set5/character4/level3.fbx'),
('set5_character4_level4', 'Model/Set5/character4/level4.fbx'),
('set5_character4_level5', 'Model/Set5/character4/level5.fbx'),

-- Pet
('Anteater_A','Model/Pets/Model/Anteater_A.fbx'),
('Anteater_B','Model/Pets/Model/Anteater_B.fbx'),
('Armadillo_A','Model/Pets/Model/Armadillo_A.fbx'),
('Armadillo_B','Model/Pets/Model/Armadillo_B.fbx'),
('Bison','Model/Pets/Model/Bison.fbx'),
('Chipmunk_A','Model/Pets/Model/Chipmunk_A.fbx'),
('Elk_A','Model/Pets/Model/Elk_A.fbx'),
('Iguana_A','Model/Pets/Model/Iguana_A.fbx'),
('Iguana_B','Model/Pets/Model/Iguana_B.fbx'),
('Malayan_A','Model/Pets/Model/Malayan_A.fbx'),
('Mole','Model/Pets/Model/Mole.fbx'),
('Otter_A','Model/Pets/Model/Otter_A.fbx'),
('Pangolin_A','Model/Pets/Model/Pangolin_A.fbx'),
('Peacock','Model/Pets/Model/Peacock.fbx'),
('Possum_A','Model/Pets/Model/Possum_A.fbx'),
('Redpanda_A','Model/Pets/Model/Redpanda_A.fbx'),
('Sloth_A','Model/Pets/Model/Sloth_A.fbx'),
('Anteater_A_Anim','Model/Pets/Animation/Anteater_A.fbx'),
('Anteater_B_Anim','Model/Pets/Animation/Anteater_B.fbx'),
('Armadillo_A_Anim','Model/Pets/Animation/Armadillo_A.fbx'),
('Armadillo_B_Anim','Model/Pets/Animation/Armadillo_B.fbx'),
('Bison_Anim','Model/Pets/Animation/Bison_Anim.fbx'),
('Chipmunk_A_Anim','Model/Pets/Animation/Chipmunk_A.fbx'),
('Elk_A_Anim','Model/Pets/Animation/Elk_Anim.fbx'),
('Iguana_A_Anim','Model/Pets/Animation/Iguana_A.fbx'),
('Iguana_B_Anim','Model/Pets/Animation/Iguana_B.fbx'),
('Malayan_A_Anim','Model/Pets/Animation/Malayan_AAnim.fbx'),
('Mole_Anim','Model/Pets/Animation/Mole.fbx'),
('Otter_A_Anim','Model/Pets/Animation/Otter_A.fbx'),
('Pangolin_A_Anim','Model/Pets/Animation/Pangolin_A.fbx'),
('Peacock_Anim','Model/Pets/Animation/PeacockAnim.fbx'),
('Possum_A_Anim','Model/Pets/Animation/Possum_A.fbx'),
('Redpanda_A_Anim','Model/Pets/Animation/Redpanda_A.fbx'),
('Sloth_A_Anim','Model/Pets/Animation/Sloth_A.fbx'),

-- Monster
('Bloom', 'Model/Monster/Model/Bloom.fbx'),
('Blossom', 'Model/Monster/Model/Blossom.fbx'),
('Bomb', 'Model/Monster/Model/Bomb.fbx'),
('Dragon_Fire', 'Model/Monster/Model/Dragon_Fire.fbx'),
('Bud', 'Model/Monster/Model/Bud.fbx'),
('Dragon_Inferno', 'Model/Monster/Model/Dragon_Inferno.fbx'),
('Dragon_Spark', 'Model/Monster/Model/Dragon_Spark.fbx'),
('Hermit_King', 'Model/Monster/Model/Hermit_King.fbx'),
('Poison_Bomb', 'Model/Monster/Model/Poison_Bomb.fbx'),
('Practice_Dummy', 'Model/Monster/Model/Practice_Dummy.fbx'),
('Shell', 'Model/Monster/Model/Shell.fbx'),
('Snake', 'Model/Monster/Model/Snake.fbx'),
('Snake_Naga', 'Model/Monster/Model/Snake_Naga.fbx'),
('Snakelet', 'Model/Monster/Model/Snakelet.fbx'),
('Snow_Bomb', 'Model/Monster/Model/Snow_Bomb.fbx'),
('Spike', 'Model/Monster/Model/Spike.fbx'),
('Sun_Blossom', 'Model/Monster/Model/Sun_Blossom.fbx'),
('Sunflora_Pixie', 'Model/Monster/Model/Sunflora_Pixie.fbx'),
('Sunflower_Fairy', 'Model/Monster/Model/Sunflower_Fairy.fbx'),
('Target_Dummy', 'Model/Monster/Model/Target_Dummy.fbx'),
('Werewolf', 'Model/Monster/Model/Werewolf.fbx'),

-- Monster Animation
('Bloom_Anim', 'Model/Monster/Animation/Bloom.fbx'),
('Blossom_Anim', 'Model/Monster/Animation/Blossom.fbx'),
('Bomb_Anim', 'Model/Monster/Animation/Bomb.fbx'),
('Dragon_Fire_Anim', 'Model/Monster/Animation/Dragon_Fire.fbx'),
('Bud_Anim', 'Model/Monster/Animation/Bud.fbx'),
('Dragon_Inferno_Anim', 'Model/Monster/Animation/Dragon_Inferno.fbx'),
('Dragon_Spark_Anim', 'Model/Monster/Animation/Dragon_Spark.fbx'),
('Hermit_King_Anim', 'Model/Monster/Animation/Hermit_King.fbx'),
('Poison_Bomb_Anim', 'Model/Monster/Animation/Poison_Bomb.fbx'),
('Practice_Dummy_Anim', 'Model/Monster/Animation/Practice_Dummy.fbx'),
('Shell_Anim', 'Model/Monster/Animation/Shell.fbx'),
('Snake_Anim', 'Model/Monster/Animation/Snake.fbx'),
('Snake_Naga_Anim', 'Model/Monster/Animation/Snake_Naga.fbx'),
('Snakelet_Anim', 'Model/Monster/Animation/Snakelet.fbx'),
('Snow_Bomb_Anim', 'Model/Monster/Animation/Snow_Bomb.fbx'),
('Spike_Anim', 'Model/Monster/Animation/Spike.fbx'),
('Sun_Blossom_Anim', 'Model/Monster/Animation/Sun_Blossom.fbx'),
('Sunflora_Pixie_Anim', 'Model/Monster/Animation/Sunflora_Pixie.fbx'),
('Sunflower_Fairy_Anim', 'Model/Monster/Animation/Sunflower_Fairy.fbx'),
('Target_Dummy_Anim', 'Model/Monster/Animation/Target_Dummy.fbx'),
('Training_Dummy_Anim', 'Model/Monster/Animation/Training_Dummy.fbx'),
('Werewolf_Anim', 'Model/Monster/Animation/Werewolf.fbx'),
('Wolf_Anim', 'Model/Monster/Animation/Wolf.fbx'),
('Wolf_Pup_Anim', 'Model/Monster/Animation/Wolf_Pup.fbx')

ON CONFLICT (model_id) DO NOTHING;

INSERT INTO game.pet (model_id) VALUES
('Anteater_A'),
('Anteater_B'),
('Armadillo_A'),
('Armadillo_B'),
('Bison'),
('Chipmunk_A'),
('Elk_A'),
('Iguana_A'),
('Iguana_B'),
('Malayan_A'),
('Mole'),
('Otter_A'),
('Pangolin_A'),
('Peacock'),
('Possum_A'),
('Redpanda_A'),
('Sloth_A')
ON CONFLICT (model_id) DO NOTHING;

INSERT INTO game.shop_price (model_id, price) VALUES
-- Set 1
('set1_character1_level1', 10),
('set1_character1_level2', 20),
('set1_character1_level3', 30),
('set1_character1_level4', 40),
('set1_character1_level5', 50),
('set1_character2_level1', 10),
('set1_character2_level2', 20),
('set1_character2_level3', 30),
('set1_character2_level4', 40),
('set1_character2_level5', 50),
('set1_character3_level1', 10),
('set1_character3_level2', 20),
('set1_character3_level3', 30),
('set1_character3_level4', 40),
('set1_character3_level5', 50),
('set1_character4_level1', 10),
('set1_character4_level2', 20),
('set1_character4_level3', 30),
('set1_character4_level4', 40),
('set1_character4_level5', 50),

-- Set 2
('set2_character1_level1', 10),
('set2_character1_level2', 20),
('set2_character1_level3', 30),
('set2_character1_level4', 40),
('set2_character1_level5', 50),
('set2_character2_level1', 10),
('set2_character2_level2', 20),
('set2_character2_level3', 30),
('set2_character2_level4', 40),
('set2_character2_level5', 50),
('set2_character3_level1', 10),
('set2_character3_level2', 20),
('set2_character3_level3', 30),
('set2_character3_level4', 40),
('set2_character3_level5', 50),
('set2_character4_level1', 10),
('set2_character4_level2', 20),
('set2_character4_level3', 30),
('set2_character4_level4', 40),
('set2_character4_level5', 50),

-- Set 3
('set3_character1_level1', 10),
('set3_character1_level2', 20),
('set3_character1_level3', 30),
('set3_character1_level4', 40),
('set3_character1_level5', 50),
('set3_character2_level1', 10),
('set3_character2_level2', 20),
('set3_character2_level3', 30),
('set3_character2_level4', 40),
('set3_character2_level5', 50),
('set3_character3_level1', 10),
('set3_character3_level2', 20),
('set3_character3_level3', 30),
('set3_character3_level4', 40),
('set3_character3_level5', 50),
('set3_character4_level1', 10),
('set3_character4_level2', 20),
('set3_character4_level3', 30),
('set3_character4_level4', 40),
('set3_character4_level5', 50),

-- Set 4
('set4_character1_level1', 10),
('set4_character1_level2', 20),
('set4_character1_level3', 30),
('set4_character1_level4', 40),
('set4_character1_level5', 50),
('set4_character2_level1', 10),
('set4_character2_level2', 20),
('set4_character2_level3', 30),
('set4_character2_level4', 40),
('set4_character2_level5', 50),
('set4_character3_level1', 10),
('set4_character3_level2', 20),
('set4_character3_level3', 30),
('set4_character3_level4', 40),
('set4_character3_level5', 50),
('set4_character4_level1', 10),
('set4_character4_level2', 20),
('set4_character4_level3', 30),
('set4_character4_level4', 40),
('set4_character4_level5', 50),

-- Set 5
('set5_character1_level1', 10),
('set5_character1_level2', 20),
('set5_character1_level3', 30),
('set5_character1_level4', 40),
('set5_character1_level5', 50),
('set5_character2_level1', 10),
('set5_character2_level2', 20),
('set5_character2_level3', 30),
('set5_character2_level4', 40),
('set5_character2_level5', 50),
('set5_character3_level1', 10),
('set5_character3_level2', 20),
('set5_character3_level3', 30),
('set5_character3_level4', 40),
('set5_character3_level5', 50),
('set5_character4_level1', 10),
('set5_character4_level2', 20),
('set5_character4_level3', 30),
('set5_character4_level4', 40),
('set5_character4_level5', 50),

-- Pet
('Anteater_A',10),
('Anteater_B',10),
('Armadillo_A',10),
('Armadillo_B',10),
('Bison',10),
('Chipmunk_A',10),
('Elk_A',10),
('Iguana_A',10),
('Iguana_B',10),
('Malayan_A',10),
('Mole',10),
('Otter_A',10),
('Pangolin_A',10),
('Peacock',10),
('Possum_A',10),
('Redpanda_A',10),
('Sloth_A',10)
ON CONFLICT (model_id) DO NOTHING;

COMMIT;