-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA "grade";

CREATE TABLE "grade"."template" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" int,
  "year" varchar,
  "template_name" varchar NOT NULL,
  "active_flag" bool,
  "version" varchar,
  "status" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "created_by" char(36) NOT NULL,
  "updated_at" timestamp,
  "updated_by" char(36),
  "admin_login_as" char(36)
);

CREATE TABLE "grade"."template_subject" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_id" int NOT NULL,
  "subject_name" varchar NOT NULL,
  "is_clever" bool NOT NULL,
  "clever_subject_id" int,
  "clever_subject_name" varchar
);

CREATE TABLE "grade"."template_general_evaluation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_id" int NOT NULL,
  "template_type" varchar NOT NULL,
  "template_name" varchar NOT NULL
);

CREATE TABLE "grade"."template_indicator" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_subject_id" int NOT NULL,
  "name" varchar NOT NULL,
  "weight" int,
  "sort" int,
  "score_evaluation_type" varchar
);

CREATE TABLE "grade"."template_assessment_setting" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_indicator_id" int NOT NULL,
  "evaluation_key" varchar,
  "evaluation_topic" varchar,
  "value" varchar,
  "weight" int
);

CREATE TABLE "grade"."general_template" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" int,
  "template_type" varchar NOT NULL,
  "template_name" varchar NOT NULL,
  "status" varchar NOT NULL,
  "active_flag" bool,
  "created_at" timestamp NOT NULL,
  "created_by" char(36) NOT NULL,
  "updated_at" timestamp,
  "updated_by" char(36),
  "admin_login_as" char(36)
);

CREATE TABLE "grade"."evaluation_form" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" int,
  "template_id" int NOT NULL,
  "academic_year" varchar NOT NULL,
  "year" varchar NOT NULL,
  "school_room" varchar NOT NULL,
  "school_term" varchar NOT NULL,
  "is_lock" bool,
  "status" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "created_by" char(36) NOT NULL,
  "updated_at" timestamp,
  "updated_by" char(36),
  "admin_login_as" char(36)
);

CREATE TABLE "grade"."evaluation_form_subject" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" int NOT NULL,
  "template_subject_id" int NOT NULL
);

CREATE TABLE "grade"."evaluation_form_general_evaluation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" int NOT NULL,
  "template_type" varchar NOT NULL,
  "template_name" varchar NOT NULL
);

CREATE TABLE "grade"."evaluation_form_additional_person" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" int NOT NULL,
  "value_type" varchar,
  "value_id" varchar,
  "user_type" varchar,
  "user_id" varchar NOT NULL
);

CREATE TABLE "grade"."evaluation_form_indicator" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evaluation_form_subject_id" int NOT NULL,
  "name" varchar NOT NULL,
  "weight" int,
  "sort" int,
  "score_evaluation_type" varchar
);

CREATE TABLE "grade"."evaluation_form_setting" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evaluation_form_indicator_id" int NOT NULL,
  "evaluation_key" varchar,
  "evaluation_topic" varchar,
  "value" varchar,
  "weight" int
);

CREATE TABLE "grade"."evaluation_form_note" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sheet_id" int NOT NULL,
  "note_value" text,
  "created_at" timestamp NOT NULL,
  "created_by" char(36) NOT NULL,
  "updated_at" timestamp,
  "updated_by" char(36)
);

CREATE TABLE "grade"."evaluation_data_entry" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sheet_id" int NOT NULL,
  "version" varchar NOT NULL,
  "json_student_score_data" text NOT NULL,
  "status" varchar NOT NULL,
  "is_lock" bool
);

CREATE TABLE "grade"."porphor5_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data_json" text,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "grade"."porphor6_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject_name" varchar,
  "student_id" varchar,
  "data_json" text,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "grade"."evaluation_student" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" int NOT NULL,
  "citizen_no" varchar,
  "student_id" varchar,
  "title" varchar,
  "thai_first_name" varchar,
  "thai_last_name" varchar,
  "eng_first_name" varchar,
  "eng_last_name" varchar,
  "birth_date" varchar,
  "nationality" varchar,
  "religion" varchar,
  "parent_marital_status" varchar
);

CREATE TABLE "grade"."evaluation_sheet" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" int NOT NULL,
  "value_type" int,
  "evaluation_form_subject_id" int,
  "evaluation_form_general_evaluation_id" int,
  "is_lock" bool,
  "status" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "created_by" char(36) NOT NULL,
  "updated_at" timestamp,
  "updated_by" char(36),
  "admin_login_as" char(36)
);

COMMENT ON TABLE "user"."user" IS 'user';

COMMENT ON COLUMN "user"."user"."title" IS 'คำนำหน้า เช่น นาน / นางสาว';

COMMENT ON COLUMN "user"."user"."id_number" IS 'เลขบัตรประชาชน';

COMMENT ON TABLE "school"."school" IS 'โรงเรียน';

COMMENT ON COLUMN "school"."school"."name" IS 'ชื่อโรงเรียน';

COMMENT ON COLUMN "school"."school"."code" IS 'รหัสย่อโรงเรียน';

COMMENT ON COLUMN "school"."school"."address" IS 'ที่อยู่';

COMMENT ON COLUMN "school"."school"."region" IS 'ภาค';

COMMENT ON COLUMN "school"."school"."province" IS 'จังหวัด';

COMMENT ON COLUMN "school"."school"."district" IS 'อำเภอ';

COMMENT ON COLUMN "school"."school"."sub_district" IS 'ตำบล';

COMMENT ON COLUMN "school"."school"."post_code" IS 'รหัสไปรษณีย์';

COMMENT ON COLUMN "school"."school"."latitude" IS 'ละติจูด';

COMMENT ON COLUMN "school"."school"."longtitude" IS 'ลองติจูด';

COMMENT ON COLUMN "school"."school"."director" IS 'ผู้อำนวยการ';

COMMENT ON COLUMN "school"."school"."director_phone_number" IS 'เบอร์ผู้อำนวยการ';

COMMENT ON COLUMN "school"."school"."registrar" IS 'นายทะเบียน';

COMMENT ON COLUMN "school"."school"."registrar_phone_number" IS 'เบอร์นายทะเบียน';

COMMENT ON COLUMN "school"."school"."academic_affair_head" IS 'หัวหน้าฝ่ายวิชาการ';

COMMENT ON COLUMN "school"."school"."academic_affair_head_phone_number" IS 'เบอร์หัวหน้าฝ่ายวิชาการ';

COMMENT ON COLUMN "school"."school"."advisor" IS 'ครูที่ปรึกษา';

COMMENT ON COLUMN "school"."school"."advisor_phone_number" IS 'เบอร์ครูที่ปรึกษา';

COMMENT ON TABLE "grade"."template" IS 'grade template (ใบตัดเกรด)';

COMMENT ON COLUMN "grade"."template"."admin_login_as" IS 'admin: ที่ทำแทน';

COMMENT ON COLUMN "grade"."template_subject"."subject_name" IS 'figma ชื่อวิชา';

COMMENT ON TABLE "grade"."template_assessment_setting" IS 'การตั้งค่าการประเมิน';

COMMENT ON TABLE "grade"."general_template" IS 'แบบประเมินทั่วไป';

COMMENT ON COLUMN "grade"."general_template"."admin_login_as" IS 'admin: ที่ทำแทน';

COMMENT ON TABLE "grade"."evaluation_form" IS 'ใบตัดเกรด';

COMMENT ON COLUMN "grade"."evaluation_form"."school_room" IS 'ห้อง 1';

COMMENT ON COLUMN "grade"."evaluation_form"."school_term" IS '1,2,SUMMER,รวมปี';

COMMENT ON COLUMN "grade"."evaluation_form"."admin_login_as" IS 'admin: ที่ทำแทน';

COMMENT ON TABLE "grade"."evaluation_form_subject" IS 'วิชา';

COMMENT ON TABLE "grade"."evaluation_form_general_evaluation" IS 'การประเมินทั่วไป';

COMMENT ON TABLE "grade"."evaluation_form_note" IS 'note ใช้ใน G0603';

COMMENT ON TABLE "grade"."evaluation_data_entry" IS 'เก็บข้อมูลเป็น json ใช้ใน G0603';

COMMENT ON COLUMN "grade"."evaluation_data_entry"."json_student_score_data" IS 'เก็บเป็น json ข้อมูลของนักเรียนพร้อมคะแนนทั้งหมด';

COMMENT ON COLUMN "grade"."evaluation_data_entry"."is_lock" IS 'ใช้ใน 06.04';

COMMENT ON TABLE "grade"."porphor5_data" IS 'batch data มาเก็บ หลังจาก ใบเกรดเป็นออกรายงานแล้ว';

COMMENT ON TABLE "grade"."porphor6_data" IS 'batch data มาเก็บ หลังจาก ใบเกรดเป็นออกรายงานแล้ว';

COMMENT ON TABLE "grade"."evaluation_student" IS 'รายชื่อนักเรียนเชื่อมต่อกับ evaluation_form';

COMMENT ON COLUMN "grade"."evaluation_student"."form_id" IS 'link for academic_year,year,room';

COMMENT ON TABLE "grade"."evaluation_sheet" IS 'ใบประเมิน ลิ้งกับ evaluation_subject, evaluation_evaluation';

COMMENT ON COLUMN "grade"."evaluation_sheet"."admin_login_as" IS 'admin: ที่ทำแทน';

ALTER TABLE "school"."school" ADD FOREIGN KEY ("created_by") REFERENCES "user"."user" ("id");

ALTER TABLE "school"."school" ADD FOREIGN KEY ("updated_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."template" ADD FOREIGN KEY ("school_id") REFERENCES "school"."school" ("id");

ALTER TABLE "grade"."template" ADD FOREIGN KEY ("created_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."template" ADD FOREIGN KEY ("updated_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."template" ADD FOREIGN KEY ("admin_login_as") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."template_subject" ADD FOREIGN KEY ("template_id") REFERENCES "grade"."template" ("id");

ALTER TABLE "grade"."template_general_evaluation" ADD FOREIGN KEY ("template_id") REFERENCES "grade"."template" ("id");

ALTER TABLE "grade"."template_indicator" ADD FOREIGN KEY ("template_subject_id") REFERENCES "grade"."template_subject" ("id");

ALTER TABLE "grade"."template_assessment_setting" ADD FOREIGN KEY ("template_indicator_id") REFERENCES "grade"."template_indicator" ("id");

ALTER TABLE "grade"."general_template" ADD FOREIGN KEY ("school_id") REFERENCES "school"."school" ("id");

ALTER TABLE "grade"."general_template" ADD FOREIGN KEY ("created_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."general_template" ADD FOREIGN KEY ("updated_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."general_template" ADD FOREIGN KEY ("admin_login_as") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_form" ADD FOREIGN KEY ("school_id") REFERENCES "school"."school" ("id");

ALTER TABLE "grade"."evaluation_form" ADD FOREIGN KEY ("template_id") REFERENCES "grade"."template" ("id");

ALTER TABLE "grade"."evaluation_form" ADD FOREIGN KEY ("created_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_form" ADD FOREIGN KEY ("updated_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_form" ADD FOREIGN KEY ("admin_login_as") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_form_subject" ADD FOREIGN KEY ("form_id") REFERENCES "grade"."evaluation_form" ("id");

ALTER TABLE "grade"."evaluation_form_subject" ADD FOREIGN KEY ("template_subject_id") REFERENCES "grade"."template_subject" ("id");

ALTER TABLE "grade"."evaluation_form_general_evaluation" ADD FOREIGN KEY ("form_id") REFERENCES "grade"."evaluation_form" ("id");

ALTER TABLE "grade"."evaluation_form_additional_person" ADD FOREIGN KEY ("form_id") REFERENCES "grade"."evaluation_form" ("id");

ALTER TABLE "grade"."evaluation_form_additional_person" ADD FOREIGN KEY ("user_id") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_form_indicator" ADD FOREIGN KEY ("evaluation_form_subject_id") REFERENCES "grade"."evaluation_form_subject" ("id");

ALTER TABLE "grade"."evaluation_form_setting" ADD FOREIGN KEY ("evaluation_form_indicator_id") REFERENCES "grade"."evaluation_form_indicator" ("id");

ALTER TABLE "grade"."evaluation_form_note" ADD FOREIGN KEY ("sheet_id") REFERENCES "grade"."evaluation_sheet" ("id");

ALTER TABLE "grade"."evaluation_form_note" ADD FOREIGN KEY ("created_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_form_note" ADD FOREIGN KEY ("updated_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_data_entry" ADD FOREIGN KEY ("sheet_id") REFERENCES "grade"."evaluation_sheet" ("id");

ALTER TABLE "grade"."evaluation_student" ADD FOREIGN KEY ("form_id") REFERENCES "grade"."evaluation_form" ("id");

ALTER TABLE "grade"."evaluation_sheet" ADD FOREIGN KEY ("form_id") REFERENCES "grade"."evaluation_form" ("id");

ALTER TABLE "grade"."evaluation_sheet" ADD FOREIGN KEY ("evaluation_form_subject_id") REFERENCES "grade"."evaluation_form_subject" ("id");

ALTER TABLE "grade"."evaluation_sheet" ADD FOREIGN KEY ("evaluation_form_general_evaluation_id") REFERENCES "grade"."evaluation_form_general_evaluation" ("id");

ALTER TABLE "grade"."evaluation_sheet" ADD FOREIGN KEY ("created_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_sheet" ADD FOREIGN KEY ("updated_by") REFERENCES "user"."user" ("id");

ALTER TABLE "grade"."evaluation_sheet" ADD FOREIGN KEY ("admin_login_as") REFERENCES "user"."user" ("id");

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "grade"."evaluation_sheet";
DROP TABLE IF EXISTS "grade"."evaluation_student";
DROP TABLE IF EXISTS "grade"."porphor6_data";
DROP TABLE IF EXISTS "grade"."porphor5_data";
DROP TABLE IF EXISTS "grade"."evaluation_data_entry";
DROP TABLE IF EXISTS "grade"."evaluation_form_note";
DROP TABLE IF EXISTS "grade"."evaluation_form_setting";
DROP TABLE IF EXISTS "grade"."evaluation_form_indicator";
DROP TABLE IF EXISTS "grade"."evaluation_form_additional_person";
DROP TABLE IF EXISTS "grade"."evaluation_form_general_evaluation";
DROP TABLE IF EXISTS "grade"."evaluation_form_subject";
DROP TABLE IF EXISTS "grade"."evaluation_form";
DROP TABLE IF EXISTS "grade"."general_template";
DROP TABLE IF EXISTS "grade"."template_assessment_setting";
DROP TABLE IF EXISTS "grade"."template_indicator";
DROP TABLE IF EXISTS "grade"."template_general_evaluation";
DROP TABLE IF EXISTS "grade"."template_subject";
DROP TABLE IF EXISTS "grade"."template";
DROP SCHEMA IF EXISTS "grade";
-- +goose StatementEnd