-- +goose Up
-- +goose StatementBegin
ALTER TABLE teacher_store.teacher_store
ADD COLUMN id INT GENERATED BY DEFAULT AS IDENTITY,
ADD COLUMN subject_id INT,
ADD COLUMN teacher_id INT,
DROP CONSTRAINT teacher_store_pkey CASCADE,
DROP COLUMN subject_teacher_id;

ALTER TABLE teacher_store.teacher_store
ADD PRIMARY KEY (id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE teacher_store.teacher_store
ADD COLUMN subject_teacher_id INT,
DROP COLUMN id;

CREATE SEQUENCE IF NOT EXISTS my_seq START WITH 1;

UPDATE teacher_store.teacher_store
SET subject_teacher_id = nextval('my_seq');;

ALTER TABLE teacher_store.teacher_store
ADD PRIMARY KEY (subject_teacher_id);

ALTER TABLE teacher_store.teacher_store
DROP COLUMN subject_id,
DROP COLUMN teacher_id;
-- +goose StatementEnd
