-- +goose Up
-- +goose StatementBegin
ALTER TABLE "item"."item"
DROP CONSTRAINT "item_teacher_item_group_id_fkey";

ALTER TABLE "teacher_item"."teacher_item_group"
DROP COLUMN "subject_teacher_id";

ALTER TABLE "teacher_item"."teacher_item_group"
ADD COLUMN "subject_id" INT REFERENCES "subject"."subject" ("id");

ALTER TABLE "teacher_item"."teacher_item_group"
ADD COLUMN "teacher_id" VARCHAR REFERENCES "user"."user" ("id");

ALTER TABLE "teacher_item"."teacher_item_group"
ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE "item"."item"
ADD CONSTRAINT item_teacher_item_group_id_fkey FOREIGN KEY ("teacher_item_group_id") REFERENCES "teacher_item"."teacher_item_group" ("id");

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE "item"."item"
DROP CONSTRAINT "item_teacher_item_group_id_fkey";

ALTER TABLE "teacher_item"."teacher_item_group"
DROP COLUMN "id";

ALTER TABLE "teacher_item"."teacher_item_group"
DROP COLUMN "teacher_id";

ALTER TABLE "teacher_item"."teacher_item_group"
DROP COLUMN "subject_id";

ALTER TABLE "teacher_item"."teacher_item_group"
ADD COLUMN "subject_teacher_id" INT;

UPDATE "teacher_item"."teacher_item_group"
SET "subject_teacher_id" = (SELECT MIN("id") FROM "subject"."subject_teacher")
WHERE "subject_teacher_id" IS NULL;

ALTER TABLE "teacher_item"."teacher_item_group"
ADD CONSTRAINT teacher_item_group_pkey PRIMARY KEY ("subject_teacher_id"),
ADD CONSTRAINT teacher_item_group_subject_teacher_id_fkey FOREIGN KEY ("subject_teacher_id") REFERENCES "subject"."subject_teacher" ("id");

ALTER TABLE "item"."item"
ADD CONSTRAINT item_teacher_item_group_id_fkey FOREIGN KEY ("teacher_item_group_id") REFERENCES "teacher_item"."teacher_item_group" ("subject_teacher_id");
-- +goose StatementEnd