-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "teacher_store"."student_teacher_shop"
(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "teacher_shop_item_id" INT NOT NULL,
    "user_id" VARCHAR(36) NOT NULL,
    FOREIGN KEY ("teacher_shop_item_id") REFERENCES "teacher_store"."teacher_store_item" ("id"),
    FOREIGN KEY ("user_id") REFERENCES "user"."user" ("id")
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "teacher_store"."student_teacher_shop";
-- +goose StatementEnd
