-- +goose Up
-- +goose StatementBegin
ALTER TABLE "grade"."document_template" RENAME COLUMN "id" TO "format_id";
ALTER TABLE "grade"."document_template" ADD COLUMN "name" VARCHAR;
ALTER TABLE "grade"."document_template" ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
DROP INDEX IF EXISTS "grade"."document_template_school_id_id_uindex";
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE "grade"."document_template" DROP CONSTRAINT IF EXISTS document_template_pkey;
ALTER TABLE "grade"."document_template" DROP COLUMN "id";
ALTER TABLE "grade"."document_template" DROP COLUMN "name";
ALTER TABLE "grade"."document_template" RENAME COLUMN "format_id" TO "id";
CREATE UNIQUE INDEX document_template_school_id_id_uindex
    ON "grade"."document_template" (school_id, id);
-- +goose StatementEnd
