-- +goose Up
-- +goose StatementBegin
DROP TABLE IF EXISTS "homework"."homework_play_log";
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "homework"."homework_play_log"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "student_id"     CHAR(36) NOT NULL REFERENCES "user"."student" ("user_id"),
    "homework_id"    INT      NOT NULL REFERENCES "homework"."homework" ("id"),
    "status"         VARCHAR  NOT NULL,
    "submitted_at"   TIMESTAMP,
    "created_by"     CHAR(36) NOT NULL REFERENCES "user"."user" ("id"),
    "admin_login_as" CHAR(36) REFERENCES "user"."user" ("id")
)
-- +goose StatementEnd