-- +goose Up
-- +goose StatementBegin

INSERT INTO "level"."level_reward" ("seed_subject_group_id",
                                    "level_type",
                                    "star_required",
                                    "gold_coin",
                                    "arcade_coin")
VALUES (1,
        'easy',
        1,
        0,
        0),
       (1,
        'easy',
        2,
        0,
        0),
       (1,
        'easy',
        3,
        0,
        0),
       (1,
        'medium',
        1,
        0,
        0),
       (1,
        'medium',
        2,
        0,
        0),
       (1,
        'medium',
        3,
        0,
        0),
       (1,
        'hard',
        1,
        0,
        0),
       (1,
        'hard',
        2,
        0,
        0),
       (1,
        'hard',
        3,
        0,
        0),
       (2,
        'easy',
        1,
        0,
        0),
       (2,
        'easy',
        2,
        0,
        0),
       (2,
        'easy',
        3,
        0,
        0),
       (2,
        'medium',
        1,
        0,
        0),
       (2,
        'medium',
        2,
        0,
        0),
       (2,
        'medium',
        3,
        0,
        0),
       (2,
        'hard',
        1,
        0,
        0),
       (2,
        'hard',
        2,
        0,
        0),
       (2,
        'hard',
        3,
        0,
        0);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
