-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "teacher_store"."study_group_teacher_shop"
(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "teacher_shop_item_id" INT NOT NULL,
    "study_group_id" INT NOT NULL,
    FOREIGN KEY ("teacher_shop_item_id") REFERENCES "teacher_store"."teacher_store_item" ("id"),
    FOREIGN KEY ("study_group_id") REFERENCES "class"."study_group" ("id")
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "teacher_store"."study_group_teacher_shop";
-- +goose StatementEnd
