-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "teacher_item"."coupon_transaction"
(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "item_id" INT NOT NULL,
    "user_id" VARCHAR(36) NOT NULL,
    "class_id" INT NOT NULL,
    "status" VARCHAR,
    "created_at" TIMESTAMP,
    FOREIGN KEY ("item_id") REFERENCES "item"."item" ("id"),
    FOREIGN KEY ("class_id") REFERENCES "class"."class" ("id")
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "teacher_item"."coupon_transaction";
-- +goose StatementEnd
