-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS "message";
CREATE TABLE "message"."messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "room_id" CHAR(36) NOT NULL,
  "sender_id" CHAR(36) NOT NULL,
  "content" VARCHAR,
  "create_at" TIMESTAMP NOT NULL,
  FOREIGN KEY ("sender_id") REFERENCES "user"."user"("id")
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "message"."messages";
DROP SCHEMA IF EXISTS "message";
-- +goose StatementEnd
