-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "grade"."subject_template"
(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "subject_id" INT NOT NULL REFERENCES "subject"."subject" ("id"),
    "seed_year_id" INT NOT NULL REFERENCES "curriculum_group"."seed_year" ("id"),
    "status" VARCHAR NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "created_by" VARCHAR(36) NOT NULL REFERENCES "user"."user" ("id"),
    "updated_at" TIMESTAMP,
    "updated_by" VARCHAR(36) REFERENCES "user"."user" ("id"),
    "wizard_index" INT
);

CREATE TABLE IF NOT EXISTS "grade"."subject_template_indicator"
(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "subject_template_id" INT NOT NULL REFERENCES "grade"."subject_template" ("id") ON DELETE CASCADE,
    "sub_lesson_id" INT REFERENCES "subject"."sub_lesson" ("id"),
    "name" VARCHAR NOT NULL,
    "type" VARCHAR NOT NULL,
    "index" INT NOT NULL,
    "value" FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS "grade"."indicator_level_setting"
(
    "subject_template_indicator_id" INT NOT NULL REFERENCES "grade"."subject_template_indicator" ("id") ON DELETE CASCADE,
    "level_type" VARCHAR NOT NULL,
    "weight" FLOAT NOT NULL,
    "levels" VARCHAR
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "grade"."indicator_level_setting";
DROP TABLE IF EXISTS "grade"."subject_template_indicator";
DROP TABLE IF EXISTS "grade"."subject_template";
-- +goose StatementEnd
