-- +goose Up
-- +goose StatementBegin
DROP TABLE IF EXISTS grade.porphor6_data;
CREATE TABLE "grade"."porphor6_data" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "form_id" integer,
    "order" integer,
    "student_id" integer,
    "data_json" text,
    "created_at" timestamp NOT NULL
);

alter table grade.porphor6_data
    add constraint porphor6_data_evaluation_form_id_fk
        foreign key (form_id) references grade.evaluation_form;

alter table grade.porphor6_data
    add constraint porphor6_data_evaluation_student_id_fk
        foreign key (student_id) references grade.evaluation_student;


-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS grade.porphor6_data;
create table grade.porphor6_data
(
    id           integer generated by default as identity
        primary key,
    subject_name varchar,
    student_id   varchar,
    data_json    text,
    created_at   timestamp not null
);

comment on table grade.porphor6_data is 'batch data มาเก็บ หลังจาก ใบเกรดเป็นออกรายงานแล้ว';

alter table grade.porphor6_data
    owner to postgres;


-- +goose StatementEnd
