-- +goose Up
-- +goose StatementBegin
drop table grade.porphor5_data;
create table grade.porphor5_data
(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id    integer
        constraint porphor5_data_evaluation_form_id_fk
            references grade.evaluation_form,
    "order"    integer,
    name       text,
    data_json  text,
    created_at timestamp
);
COMMENT ON TABLE "grade"."porphor5_data" IS 'เก็บ หลังจาก ใบเกรดเป็นออกรายงานแล้ว';
COMMENT ON COLUMN "grade"."porphor5_data"."order" IS 'ลำดับในการแสดงชื่อของแท็บบนหน้าจอ';
COMMENT ON COLUMN "grade"."porphor5_data"."name" IS 'ชื่อที่จะแสดงบนหน้าจอ';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table grade.porphor5_data;
CREATE TABLE "grade"."porphor5_data" (
                                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "data_json" text,
                                         "created_at" timestamp NOT NULL
);
COMMENT ON TABLE "grade"."porphor5_data" IS 'batch data มาเก็บ หลังจาก ใบเกรดเป็นออกรายงานแล้ว';

-- +goose StatementEnd
