-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS "reward";
CREATE TABLE IF NOT EXISTS "reward"."reward_log"
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            CHAR(36) NOT NULL REFERENCES "user"."user" ("id"),
    gold_coin_amount   INT,
    arcade_coin_amount INT,
    ice_amount         INT,
    item_id            INT REFERENCES "item"."item" ("id"),
    item_amount        INT,
    avatar_id          INT REFERENCES "game"."avatar" ("id"),
    avatar_amount      INT,
    pet_id             INT REFERENCES "game"."pet" ("id"),
    pet_amount         INT,
    description        VARCHAR,
    received_at        TIMESTAMP NOT NULL,
    created_at         TIMESTAMP NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "reward"."reward_log";
DROP SCHEMA IF EXISTS "reward";
-- +goose StatementEnd
