-- +goose Up
-- +goose StatementBegin
ALTER TABLE "level"."teacher_note" DROP CONSTRAINT teacher_note_pkey;
ALTER TABLE "level"."teacher_note" ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE "level"."teacher_note" DROP COLUMN "id";
ALTER TABLE "level"."teacher_note" ADD CONSTRAINT teacher_note_pkey PRIMARY KEY ("teacher_id", "student_id");
-- +goose StatementEnd
