-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "bug"."bug_report_image"
(
    "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bug_report_id" INT NOT NULL REFERENCES "bug"."bug_report" ("id"),
    "image_url"     VARCHAR NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "bug"."bug_report_image";
-- +goose StatementEnd
