-- role_id = 4 : Administrator
INSERT INTO bss_mst_role_permission
   (
      role_id      ,
      menu_id      ,
      assigned_date,
      is_active    ,
      created_by   ,
      created_date
   )
VALUES
(4,8,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- รายงาน
(4,9,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- User and Access
(4,10,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Machine
(4,11,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Institution and Banknote
(4,12,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Setting
(4,25,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Single Header Card Report
(4,26,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Multi Header Card Report
(4,39,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Company
(4,40,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Company Department
(4,41,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Department
(4,42,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Menu
(4,43,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Role Group
(4,44,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Role
(4,45,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Role Permission
(4,46,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master User
(4,47,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Machine Type
(4,48,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master M7 Output Data
(4,49,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master M7 Quality
(4,50,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Machine
(4,51,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Institution
(4,52,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Company Institution
(4,53,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Cash Center
(4,54,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Cash Point
(4,55,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Series Denom
(4,56,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master M7Denom Series
(4,57,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Denomination
(4,58,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Banknote Type
(4,59,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Banknote Type Send
(4,60,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Denom Reconcile
(4,61,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master M7 Denomination
(4,62,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- MasterZone
(4,63,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- MasterZoneCashPoint
(4,64,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Cash Type
(4,65,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Config Type
(4,66,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Config
(4,67,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP), -- Master Status
(4,68,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP);  -- Master Shift