INSERT INTO [BSSDEVDB].[dbo].[bss_mst_status]
([status_code], [status_name_en], [status_name_th], [is_active], [created_by], [created_date], [updated_by], [updated_date])
VALUES
('01', N'Registered', N'ลงทะเบียน', 1, 1, GETDATE(), NULL, NULL),
('02', N'Delivered Note', N'สร้างใบส่งมอบ', 1, 1, GETDATE(), NULL, NULL),
('03', N'Delivered', N'ส่งมอบ', 1, 1, GETDATE(), NULL, NULL),
('04', N'Correct Return', N'แก้ไขรายการส่งกลับ', 1, 1, GETDATE(), NULL, NULL),
('05', N'Returned', N'ส่งคืน/ไม่รับมอบ', 1, 1, GETDATE(), NULL, NULL),
('06', N'Received', N'รับมอบ', 1, 1, GETDATE(), NULL, NULL),
('07', N'Finished', N'สิ้นสุด', 1, 1, GETDATE(), NULL, NULL),
('08', N'Deleted Pre-Prepare', N'ลบข้อมูลภาชนะ', 1, 1, GETDATE(), NULL, NULL),
('09', N'Prepared', N'เตรียมธนบัตร', 1, 1, GETDATE(), NULL, NULL),
('10', N'Cancel Prepared', N'ยกเลิกเตรียมธนบัตร', 1, 1, GETDATE(), NULL, NULL),
('11', N'Reconciliation', N'รายการรอกระทบยอด', 1, 1, GETDATE(), NULL, NULL),
('12', N'Cancel Reconciliation', N'ยกเลิกรายการรอกระทบยอด', 1, 1, GETDATE(), NULL, NULL),
('13', N'Reconciled', N'กระทบยอดแล้ว', 1, 1, GETDATE(), NULL, NULL),
('14', N'Auto Selling', N'Auto Selling', 1, 1, GETDATE(), NULL, NULL),
('15', N'Adjust Offset', N'Adjust Offset', 1, 1, GETDATE(), NULL, NULL),
('16', N'Approved', N'อนุมัติ', 1, 1, GETDATE(), NULL, NULL),
('17', N'Verify', N'Verify', 1, 1, GETDATE(), NULL, NULL),
('18', N'Send To CBMS', N'ส่งผลนับคัดเข้า CBMS', 1, 1, GETDATE(), NULL, NULL),
('19', N'Confirm', N'ยืนยันผลนับคัด', 1, 1, GETDATE(), NULL, NULL),
('20', N'Edited', N'แก้ไขข้อมูลผลนับคัด', 1, 1, GETDATE(), NULL, NULL),
('21', N'Denied Edited', N'ไม่อนุมัติแก้ไขข้อมูลผลนับคัด', 1, 1, GETDATE(), NULL, NULL),
('22', N'Cancel Sent Denied Edited', N'ยกเลิกผลนับคัดที่แก้ไข', 1, 1, GETDATE(), NULL, NULL),
('23', N'Cancel Sent', N'ยกเลิกส่งผลนับคัด', 1, 1, GETDATE(), NULL, NULL),
('24', N'Manual Key-in', N'แก้ไขข้อมูล Manual Key-in', 1, 1, GETDATE(), NULL, NULL),
('25', N'Denied Manual Key-in', N'ไม่อนุมัติผลแก้ไข Manual Key-in', 1, 1, GETDATE(), NULL, NULL),
('26', N'Cancel Sent Manual Key-in', N'ยกเลิกส่งผลนับคัด Manual Key-in', 1, 1, GETDATE(), NULL, NULL),
('27', N'Edited Approved', N'แก้ไขข้อมูลที่อนุมัติแล้ว', 1, 1, GETDATE(), NULL, NULL),
('28', N'Denied Edited Approved', N'ไม่อนุมัติผลแก้ไขอนุมัติแล้ว', 1, 1, GETDATE(), NULL, NULL),
('29', N'Cancel Sent Denied Approved', N'ยกเลิกผลนับคัดที่อนุมัติแล้ว', 1, 1, GETDATE(), NULL, NULL),
('30', N'Approved Cancel', N'อนุมัติยกเลิกส่งผลนับคัด', 1, 1, GETDATE(), NULL, NULL);