#!/bin/sh
# pre-start.sh — รันบน HOST ก่อนสร้าง container (via initializeCommand)
# ตรวจ OS แล้ว generate docker-compose.devcontainer.yml ที่ mount .claude credentials

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ -n "$USERPROFILE" ]; then
  # Windows: ใช้ USERPROFILE (ไม่ใช้ HOME เพราะ Git for Windows set ทับ)
  CLAUDE_HOME="$(echo "$USERPROFILE" | tr '\\' '/')"
else
  # Mac / Linux
  CLAUDE_HOME="$HOME"
fi

cat > "$SCRIPT_DIR/docker-compose.devcontainer.yml" <<EOF
# AUTO-GENERATED by pre-start.sh — อย่าแก้มือ
services:
  app:
    volumes:
      - ${CLAUDE_HOME}/.claude:/home/vscode/.claude:cached
EOF

# ซ่อน local changes จาก git status
git update-index --skip-worktree .devcontainer/docker-compose.devcontainer.yml 2>/dev/null || true

# Copy .env so docker-compose can resolve ${...} vars
# (compose looks for .env next to the compose file, i.e. .devcontainer/)
cp "$SCRIPT_DIR/../.env" "$SCRIPT_DIR/.env" 2>/dev/null || true

echo "[pre-start] OS detected -> CLAUDE_HOME=$CLAUDE_HOME"
echo "[pre-start] Generated docker-compose.devcontainer.yml"
