name: DEVELOPMENT-CI

on:
  pull_request:
    branches: ['production']
  workflow_dispatch:

jobs:
  typescript-check:
    name: Test
    uses: ZettaMerge/2024-05-clever-platform-cicd/.github/workflows/npm-type-check.yml@main
    with:
      version: '22.14.0'
      script-name: type-check
      working-dir: .

  build:
    name: Build
    needs: typescript-check
    uses: ZettaMerge/2024-05-clever-platform-cicd/.github/workflows/frontend-build.yml@main
    with:
      version: '22.14.0'
      build-output-path: dist
      build-output-name: clever-frontend-build
      working-dir: .
      script-name: build:no-tsc

    secrets:
      VITE_API_BASE_URL: ${{secrets.PROD_VITE_API_BASE_URL}}
      VITE_DEBUG_API_IS_MOCK: ${{secrets.PROD_VITE_DEBUG_API_IS_MOCK}}
      VITE_CLMS_BASE_URL: ${{secrets.PROD_VITE_CLMS_BASE_URL}}
      VITE_LINK_LINE_OA_URL: ${{secrets.PROD_VITE_LINK_LINE_OA_URL}}
      SERVER_USER: ${{ secrets.HOST_STAGING_USERNAME }}
      SERVER_HOST: ${{ secrets.HOST_STAGING_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.HOST_STAGING_SSH_KEY }}
