CREATE TABLE bss_txn_reconcile_tran (
    reconcile_tran_id BIGINT PRIMARY KEY IDENTITY(1,1),
    department_id INT NOT NULL,
    prepare_id BIGINT NOT NULL,
    machine_hd_id BIGINT NOT NULL,
    header_card_code NVARCHAR(15),
    header_parent_id BIGINT,
    m7_qty INT,
    reconcile_qty INT,
    sup_qty INT,
    bundle_num INT,
    rec_total_value INT,
    status_id INT NOT NULL,
    approve_by INT,
    approve_date DATETIME,
    reference_code NVARCHAR(20),
    sorter_id INT,
    shift_id INT NOT NULL,
    remark NVARCHAR(300),
    alert_remark NVARCHAR(1000),
    is_display BIT DEFAULT 1,
    is_active BIT,
    is_revoke BIT,
    created_by INT NOT NULL,
    created_date DATETIME NOT NULL DEFAULT GETDATE(),
    updated_by INT,
    updated_date DATETIME,
    
    -- Foreign Key Constraints
    CONSTRAINT FK_reconcile_tran_department FOREIGN KEY (department_id) REFERENCES bss_mst_bn_operation_center(department_id),
    CONSTRAINT FK_reconcile_tran_prepare FOREIGN KEY (prepare_id) REFERENCES bss_txn_prepare(prepare_id),
    CONSTRAINT FK_reconcile_tran_machine_hd FOREIGN KEY (machine_hd_id) REFERENCES bss_txn_machine_hd(machine_hd_id),
    CONSTRAINT FK_reconcile_tran_status FOREIGN KEY (status_id) REFERENCES bss_mst_status(status_id),
    CONSTRAINT FK_reconcile_tran_shift FOREIGN KEY (shift_id) REFERENCES bss_mst_shift(shift_id)
);