import {
  ColorSettings,
  score_type,
  TDocumentTemplate,
  TTemplateProps,
} from '@domain/g06/g06-d07/local/types/template';
import template1Image from '../../../local/assets/template1.png';
import template2Image from '../../../local/assets/template2.png';
import template3Image from '../../../local/assets/template3.png';
import { at } from 'lodash';

export const templateOptions = [
  { label: 'Template 1', value: '1' },
  { label: 'Template 2', value: '2' },
  { label: 'Template 3', value: '3' },
];
export const templateImage = [
  { id: '1', value: '1', name: 'แบบที่ 1', image: template1Image },
  { id: '2', value: '2', name: 'แบบที่ 2', image: template2Image },
  { id: '3', value: '3', name: 'แบบที่ 3', image: template3Image },
];

export const colorGroups = [
  { name: 'position1', label: 'เปลี่ยนสีเอกสาร' },
  { name: 'position2', label: 'สีพื้นหลังท้ายเอกสาร' },
  { name: 'position3', label: 'สีพื้นหลังหัวข้อเอกสาร' },
];

export const defaultColorSettings: ColorSettings = {
  position1: '',
  position2: '',
  position3: '',
};
export const colorShades = [
  '#F1F0FF',
  '#F0FAFF',
  '#F0FFF3',
  '#FFFEF0',
  '#FFF0F0',
  '#FEF0FF',
];
export const mockData: Partial<TDocumentTemplate> = {
  school_id: 1,
  format_id: undefined,
  name: 'Green',
  logo_image: null,
  background_image: null,
  colour_setting: { position1: 'RRR', position2: '000000' },
  created_at: '2025-08-13T04:05:33.504802Z',
  created_by: '00f1b13e-0e62-45d2-9718-099cd545b3ac',
  updated_at: '2025-08-14T04:30:14.651945Z',
  updated_by: 'gmmm',
  is_default: true,
};
export const studentDataTemplate = {
  id: '101110',
  name: 'เกศินี ขุนเพิ่ม',
  number: '1',
  province: 'จังหวัดกรุงเทพมหานคร',
};
export const summaryDataTemplate = {
  basicCredits: 21,
  additionalCredits: 6,
  totalCredits: 27,
  gpa: '3.70',
  evaluations: {
    socialMental: 'ดีเยี่ยม',
    workEthics: 'ดีเยี่ยม',
    skillDevelopment: 'ดีเยี่ยม',
  },
};
export const signaturesDataTemplate = {
  homeroom: { name: 'นายหนุ่ง บุญเสริม', position: 'ครูประจําชั้น' },
  head: { name: 'นายหนุ่ง บุญเสริม', position: 'หัวหน้างานวิชาการโรงเรียน' },
  project: { name: 'นางสาวจุฬารัตน์ แก่นจันทร์', position: 'ครูประจําโครงการศึกษา' },
  director: { name: 'นายหนุ่ง บุญเสริม', position: 'ผู้อำนวยการโรงเรียน' },
};

export const TemplateScores = [
  {
    subject_code: '121543',
    subject: 'วิทยาศาสตร์',
    study_time: 246,
    study_total: '100.00',
    weight: 4,
    semester1: 49,
    semester2: 31,
    total: 80,
    grade: 4,
    type: score_type.standard,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
  {
    subject_code: '121543',
    subject: 'คณิตศาสตร์',
    study_time: 130,
    study_total: '100.00',
    weight: 4,
    semester1: 26,
    semester2: 42,
    total: 68,
    grade: 2.5,
    type: score_type.standard,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
  {
    subject_code: '121543',
    subject: 'ภาษาไทย',
    study_time: 156,
    study_total: '100.00',
    weight: 2,
    semester1: 45,
    semester2: 33,
    total: 78,
    grade: 3.5,
    type: score_type.standard,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
  {
    subject_code: '121543',
    subject: 'ประวัติศาสตร์',
    study_time: 203,
    study_total: '100.00',
    weight: 1,
    semester1: 33,
    semester2: 43,
    total: 76,
    grade: 3.5,
    type: score_type.standard,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
  {
    subject_code: '121543',
    subject: 'สุขศึกษาและพลศึกษา',
    study_time: 108,
    study_total: '100.00',
    weight: 2,
    semester1: 40,
    semester2: 41,
    total: 81,
    grade: 4,
    type: score_type.standard,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
  {
    subject_code: '121543',
    subject: 'ศิลปะ',
    study_time: 69,
    study_total: '100.00',
    weight: 2,
    semester1: 40,
    semester2: 47,
    total: 87,
    grade: 4,
    type: score_type.standard,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
  {
    subject_code: '121543',
    subject: 'การงานอาชีพ',
    study_time: 132,
    study_total: '100.00',
    weight: 2,
    semester1: 47,
    semester2: 45,
    total: 92,
    grade: 4,
    type: score_type.extra,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
  {
    subject_code: '121543',
    subject: 'ภาษาอังกฤษ',
    study_time: 108,
    study_total: '100.00',
    weight: 2,
    semester1: 39,
    semester2: 42,
    total: 81,
    grade: 4,
    type: score_type.standard,
    normal_score: '95',
    exam_score: '85',
    retest_score: '90',
    attribute: '3',
    read_things: '3',
  },
];
