import { LevelType, Monster, Map, SubjectType } from '../../Type';

export const MapData: Map[] = [
  // คณิต
  {
    id: 1,
    seed_subject_group_id: 1,
    map_name: 'ทางเดิน (ค่าเริ่มต้น)',
    image_path: '/assets/images/background/subject-group-1/1-4-default.png',
    available_for: [SubjectType.MATH],
  },
  {
    id: 2,
    seed_subject_group_id: 1,
    map_name: 'ทางเดิน 1.1',
    image_path: '/assets/images/background/subject-group-1/1-1.png',
    available_for: [SubjectType.MATH],
  },
  {
    id: 3,
    seed_subject_group_id: 1,
    map_name: 'ทางเดิน 1.2',
    image_path: '/assets/images/background/subject-group-1/1-2.png',
    available_for: [SubjectType.MATH],
  },
  {
    id: 4,
    seed_subject_group_id: 1,
    map_name: 'ทางเดิน 1.3',
    image_path: '/assets/images/background/subject-group-1/1-3.png',
    available_for: [SubjectType.MATH],
  },

  {
    id: 5,
    seed_subject_group_id: 1,
    map_name: 'ทางเดิน 1.5',
    image_path: '/assets/images/background/subject-group-1/1-5.png',
    available_for: [SubjectType.MATH],
  },
  // อังกฤษ
  {
    id: 6,
    seed_subject_group_id: 2,
    map_name: 'ภูเขา (ค่าเริ่มต้น)',
    image_path: '/assets/images/background/subject-group-2/2-3-default.png',
    available_for: [SubjectType.ENG],
  },
  {
    id: 7,
    seed_subject_group_id: 2,
    map_name: 'ภูเขา 2.1',
    image_path: '/assets/images/background/subject-group-2/2-1.png',
    available_for: [SubjectType.ENG],
  },
  {
    id: 8,
    seed_subject_group_id: 2,
    map_name: 'ภูเขา 2.2',
    image_path: '/assets/images/background/subject-group-2/2-2.png',
    available_for: [SubjectType.ENG],
  },

  {
    id: 9,
    seed_subject_group_id: 2,
    map_name: 'ภูเขา 2.4',
    image_path: '/assets/images/background/subject-group-2/2-4.png',
    available_for: [SubjectType.ENG],
  },
  {
    id: 10,
    seed_subject_group_id: 2,
    map_name: 'ภูเขา 2.5',
    image_path: '/assets/images/background/subject-group-2/2-5.png',
    available_for: [SubjectType.ENG],
  },

  // จีน
  {
    id: 11,
    seed_subject_group_id: 3,
    map_name: 'ทุ่งหญ้า (ค่าเริ่มต้น)',
    image_path: '/assets/images/background/subject-group-3/3-2-default.png',
    available_for: [SubjectType.CHINESE],
  },
  {
    id: 12,
    seed_subject_group_id: 3,
    map_name: 'ทุ่งหญ้า 3.1',
    image_path: '/assets/images/background/subject-group-3/3-1.png',
    available_for: [SubjectType.CHINESE],
  },

  {
    id: 13,
    seed_subject_group_id: 3,
    map_name: 'ทุ่งหญ้า 3.3',
    image_path: '/assets/images/background/subject-group-3/3-3.png',
    available_for: [SubjectType.CHINESE],
  },
  {
    id: 14,
    seed_subject_group_id: 3,
    map_name: 'ทุ่งหญ้า 3.4',
    image_path: '/assets/images/background/subject-group-3/3-4.png',
    available_for: [SubjectType.CHINESE],
  },
  {
    id: 15,
    seed_subject_group_id: 3,
    map_name: 'ทุ่งหญ้า 3.5',
    image_path: '/assets/images/background/subject-group-3/3-5.png',
    available_for: [SubjectType.CHINESE],
  },
  // จีน
  {
    id: 16,
    seed_subject_group_id: 4,
    map_name: 'ชายหาด (ค่าเริ่มต้น)',
    image_path: '/assets/images/background/subject-group-4/4-5-default.png',
    available_for: [SubjectType.SCIENCE],
  },
  {
    id: 17,
    seed_subject_group_id: 4,
    map_name: 'ชายหาด 4.1',
    image_path: '/assets/images/background/subject-group-4/4-1.png',
    available_for: [SubjectType.SCIENCE],
  },
  {
    id: 18,
    seed_subject_group_id: 4,
    map_name: 'ชายหาด 4.2',
    image_path: '/assets/images/background/subject-group-4/4-2.png',
    available_for: [SubjectType.SCIENCE],
  },
  {
    id: 19,
    seed_subject_group_id: 4,
    map_name: 'ชายหาด 4.3',
    image_path: '/assets/images/background/subject-group-4/4-3.png',
    available_for: [SubjectType.SCIENCE],
  },
  {
    id: 20,
    seed_subject_group_id: 4,
    map_name: 'ชายหาด 4.4',
    image_path: '/assets/images/background/subject-group-4/4-4.png',
    available_for: [SubjectType.SCIENCE],
  },
];
export const MonsterData: Monster[] = [
  {
    id: 1,
    name: 'Sun Blossom',
    name_model: 'Sun_Blossom',
    image_path: '/assets/images/monster/test-monsters/sun-blossom.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },
  {
    id: 2,
    name: 'Shell',
    name_model: 'Shell',
    image_path: '/assets/images/monster/test-monsters/shell.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },
  {
    id: 3,
    name: 'Snakelet',
    name_model: 'Snakelet',
    image_path: '/assets/images/monster/test-monsters/snakelet.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },
  {
    id: 4,
    name: 'Bud',
    name_model: 'Bud',
    image_path: '/assets/images/monster/test-monsters/bud.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },
  {
    id: 5,
    name: 'Practice-Dummy',
    name_model: 'Practice_Dummy',
    image_path: '/assets/images/monster/test-monsters/practice-dummy.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },
  {
    id: 6,
    name: 'Wolf Pup',
    name_model: 'Wolf_Pup',
    image_path: '/assets/images/monster/test-monsters/wolf-pup.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },
  {
    id: 7,
    name: 'Dragon Spark',
    name_model: 'Dragon_Spark',
    image_path: '/assets/images/monster/test-monsters/dragon-spark.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },
  {
    id: 8,
    name: 'Snow Bomb',
    name_model: 'Snow_Bomb',
    image_path: '/assets/images/monster/test-monsters/snow-bomb.png',
    level_type: LevelType.TEST,
    available_for: [LevelType.TEST],
  },

  {
    id: 9,
    name: 'Sun Blossom',
    name_model: 'Sun_Blossom',
    image_path: '/assets/images/monster/pre-test-monsters/sunflower-fairy.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },
  {
    id: 10,
    name: 'Spike',
    name_model: 'Spike',
    image_path: '/assets/images/monster/pre-test-monsters/spike.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },
  {
    id: 11,
    name: 'Snake',
    name_model: 'Snake',
    image_path: '/assets/images/monster/pre-test-monsters/snake.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },
  {
    id: 12,
    name: 'Bloom',
    name_model: 'Bloom',
    image_path: '/assets/images/monster/pre-test-monsters/bloom.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },
  {
    id: 13,
    name: 'Target Dummy',
    name_model: 'Target_Dummy',
    image_path: '/assets/images/monster/pre-test-monsters/target-dummy.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },
  {
    id: 14,
    name: 'Wolf',
    name_model: 'Wolf',
    image_path: '/assets/images/monster/pre-test-monsters/wolf.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },
  {
    id: 15,
    name: 'Dragon Fire',
    name_model: 'Dragon_Fire',
    image_path: '/assets/images/monster/pre-test-monsters/dragon-fire.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },
  {
    id: 16,
    name: 'Boomer',
    name_model: 'Boomer',
    image_path: '/assets/images/monster/pre-test-monsters/boomer.png',
    level_type: LevelType.PRETEST,
    available_for: [LevelType.PRETEST],
  },

  {
    id: 17,
    name: 'Sunflora Pixie',
    name_model: 'Sunflora_Pixie',
    image_path: '/assets/images/monster/post-test-monsters/sunflora-pixie.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
  {
    id: 18,
    name: 'Hermit King',
    name_model: 'Hermit_King',
    image_path: '/assets/images/monster/post-test-monsters/hermit-king.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
  {
    id: 19,
    name: 'Snake Naga',
    name_model: 'Snake_Naga',
    image_path: '/assets/images/monster/post-test-monsters/snake-naga.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
  {
    id: 20,
    name: 'Blossom',
    name_model: 'Blossom',
    image_path: '/assets/images/monster/post-test-monsters/blossom.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
  {
    id: 21,
    name: 'Training Dummy',
    name_model: 'Training_Dummy',
    image_path: '/assets/images/monster/post-test-monsters/training-dummy.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
  {
    id: 22,
    name: 'Werewolf',
    name_model: 'Werewolf',
    image_path: '/assets/images/monster/post-test-monsters/werewolf.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
  {
    id: 23,
    name: 'Dragon Inferno',
    name_model: 'Dragon_Inferno',
    image_path: '/assets/images/monster/post-test-monsters/dragon-inferno.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
  {
    id: 24,
    name: 'Poison Bomb',
    name_model: 'Poison_Bomb',
    image_path: '/assets/images/monster/post-test-monsters/poison-bomb.png',
    level_type: LevelType.POSTTEST,
    available_for: [LevelType.POSTTEST],
  },
];
export const optionFontFamily = [
  { value: 'noto-sans-thai', label: 'Noto Sans Thai' },
  { value: 'san', label: 'San' },
  { value: 'latin', label: 'Latin' },
];

export const optionFontsize = [
  { value: '16pt', label: '16 pt - Size S (เหมาะสำหรับวัยรุ่น)' },
  { value: '22pt', label: '22 pt - Size M (เหมาะสำหรับเด็กประถมและมัธยม)' },
  { value: '24pt', label: '24 pt - Size L (เหมาะสำหรับวัยกลางคน)' },
  { value: '26pt', label: '26 pt - Size XL (เหมาะสำหรับเด็กเล็กประถมต้นหรือผู้สูงอายุ)' },
];

export const optionAccessibility = [
  { value: '', label: 'พื้นฐาน (standard)' },
  { value: '(extra)', label: 'พิเศษ (extra)' },
];
