CREATE TABLE bss_txn_prepare (
    prepare_id BIGINT IDENTITY(1,1) PRIMARY KEY,
    container_prepare_id BIGINT NOT NULL,
    header_card_code NVARCHAR(15) NOT NULL,
    package_code NVARCHAR(20) NOT NULL,
    bundle_code NVARCHAR(30) NOT NULL,
    inst_id INTEGER NOT NULL,
    cashcenter_id INTEGER,
    zone_id INTEGER,
    cashpoint_id INTEGER,
    deno_id INTEGER NOT NULL,
    qty INTEGER NOT NULL,
    remark NVARCHAR(300),
    status_id INTEGER NOT NULL,
    prepare_date DATETIME NOT NULL,
    unsort_cc_id BIGINT Null,
    is_active BIT,
    created_by INTEGER,
    created_date DATETIME NOT NULL,
    updated_by INTEGER,
    updated_date DATETIME,
    is_reconcile BIT,
    CONSTRAINT FK_bss_txn_prepare_container_prepare FOREIGN KEY (container_prepare_id) REFERENCES bss_txn_container_prepare(container_prepare_id),
    CONSTRAINT FK_bss_txn_prepare_inst FOREIGN KEY (inst_id) REFERENCES bss_mst_institution(inst_id),
    CONSTRAINT FK_bss_txn_prepare_cashcenter FOREIGN KEY (cashcenter_id) REFERENCES bss_mst_cashcenter(cashcenter_id),
    CONSTRAINT FK_bss_txn_prepare_cashpoint FOREIGN KEY (cashpoint_id) REFERENCES bss_mst_cashpoint(cashpoint_id),
    CONSTRAINT FK_bss_txn_prepare_deno FOREIGN KEY (deno_id) REFERENCES bss_mst_denomination(deno_id),
    CONSTRAINT FK_bss_txn_prepare_status FOREIGN KEY (status_id) REFERENCES bss_mst_status(status_id),
    CONSTRAINT FK_bss_txn_prepare_zone FOREIGN KEY (zone_id) REFERENCES bss_mst_zone(zone_id),
    CONSTRAINT FK_bss_txn_prepare_unsort_cc_id_txn_unsort_cc FOREIGN KEY (unsort_cc_id) REFERENCES bss_txn_unsort_cc (unsort_cc_id)
    
);