name: STAGING-CD

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  build:
    name: Build & Deploy
    uses: ZettaMerge/2024-05-clever-platform-cicd/.github/workflows/backoffice-build-deploy.yml@main
    with:
      version: "22.14.0"
      build-output-path: dist
      build-output-name: clever-backoffice-build
      working-dir: "v1"
      script-name: build:no-tsc
      destination: /var/www/clever-staging-backoffice

    secrets:
      VITE_API_BASE_URL: ${{secrets.STAGING_VITE_API_BASE_URL}}
      VITE_GAME_BASE_URL: ${{secrets.STAGING_VITE_GAME_BASE_URL}}
      VITE_WS_BASE_URL: ${{secrets.STAGING_VITE_WS_BASE_URL}}
      VITE_DEBUG_API_IS_MOCK: ${{secrets.STAGING_VITE_DEBUG_API_IS_MOCK}}
      VITE_LINE_LIFF_ID: ${{secrets.STAGING_VITE_LINE_LIFF_ID}}
      SERVER_USER: ${{ secrets.HOST_STAGING_USERNAME }}
      SERVER_HOST: ${{ secrets.HOST_STAGING_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.HOST_STAGING_SSH_KEY }}
